import type { Vet } from './schema'

export const vetsMock: Vet[] = [
  {
    id: 'vet-songpa-park',
    name: '박지영 수의사',
    clinic: '송파특수동물의료센터',
    specialties: ['파충류', '양서류', '절지류'],
    yearsOfExperience: 11,
    status: 'online',
    avatarEmoji: '👩‍⚕️',
    hourlyKrw: 35000,
  },
  {
    id: 'vet-cheongdam-lee',
    name: '이준호 수의사',
    clinic: '청담우리동물병원 (특수동물과)',
    specialties: ['조류', '소형 포유류'],
    yearsOfExperience: 8,
    status: 'busy',
    avatarEmoji: '👨‍⚕️',
    hourlyKrw: 40000,
  },
  {
    id: 'vet-bundang-han',
    name: '한지수 수의사',
    clinic: '분당특수동물병원',
    specialties: ['파충류', '소형 포유류'],
    yearsOfExperience: 6,
    status: 'online',
    avatarEmoji: '👩‍⚕️',
    hourlyKrw: 30000,
  },
  {
    id: 'vet-mokdong-choi',
    name: '최가람 수의사',
    clinic: '목동파충류전문병원',
    specialties: ['파충류', '양서류'],
    yearsOfExperience: 14,
    status: 'offline',
    avatarEmoji: '👨‍⚕️',
    hourlyKrw: 38000,
  },
  {
    id: 'vet-mapo-kang',
    name: '강민서 수의사',
    clinic: '마포24시동물의료원',
    specialties: ['응급', '조류', '파충류'],
    yearsOfExperience: 9,
    status: 'online',
    avatarEmoji: '🧑‍⚕️',
    hourlyKrw: 45000,
  },
]
