import type { Shop } from './schema'

export const shopsMock: Shop[] = [
  {
    id: 'sh-jamsil-reptile',
    name: '잠실파충류전문샵',
    kind: 'both',
    address: '서울 송파구 송파대로 567',
    district: '서울 송파구',
    lat: 37.5097,
    lng: 127.106,
    online: 'https://smartstore.naver.com/jamsil-reptile',
    supportedCategories: ['reptile', 'amphibian'],
    notes: '현장 픽업/택배 모두 가능. 사육장·UVB·먹이 풀라인업.',
  },
  {
    id: 'sh-songpa-bugshop',
    name: '송파곤충마켓',
    kind: 'food',
    address: '서울 송파구 백제고분로 320',
    district: '서울 송파구',
    lat: 37.5074,
    lng: 127.1129,
    online: 'https://buggy.kr',
    supportedCategories: ['reptile', 'arthropod', 'bird'],
    notes: '귀뚜라미·둠비아·밀웜 정기 배송. 살아있는 먹이 신선도 보장.',
  },
  {
    id: 'sh-gangnam-birdmarket',
    name: '강남조류마켓',
    kind: 'equipment',
    address: '서울 강남구 테헤란로 152',
    district: '서울 강남구',
    lat: 37.5006,
    lng: 127.0364,
    online: 'https://birdmarket.kr',
    supportedCategories: ['bird'],
    notes: '대형 새장·횃대·자유비행용 케이지 전문.',
  },
  {
    id: 'sh-bundang-petplus',
    name: '분당특수동물용품샵',
    kind: 'both',
    address: '경기 성남시 분당구 정자로 100',
    district: '경기 성남시 분당구',
    lat: 37.3603,
    lng: 127.1188,
    online: null,
    supportedCategories: ['reptile', 'mammal', 'amphibian'],
    notes: '오프라인 매장에서 사육 환경 상담 가능.',
  },
  {
    id: 'sh-online-pettrarium',
    name: '펫트라리움 (온라인)',
    kind: 'both',
    address: null,
    district: null,
    lat: null,
    lng: null,
    online: 'https://pettrarium.com',
    supportedCategories: ['reptile', 'amphibian', 'arthropod'],
    notes: '온라인 전용 사육장·온습도계·UV램프 전문몰.',
  },
  {
    id: 'sh-online-cgd',
    name: 'Repashy CGD 코리아',
    kind: 'food',
    address: null,
    district: null,
    lat: null,
    lng: null,
    online: 'https://repashy.kr',
    supportedCategories: ['reptile'],
    notes: '크레스티드 게코 다이어트(CGD) 정품 수입 판매.',
  },
  {
    id: 'sh-online-axolotl',
    name: '아쿠아펫몰',
    kind: 'both',
    address: null,
    district: null,
    lat: null,
    lng: null,
    online: 'https://aquapetmall.kr',
    supportedCategories: ['amphibian'],
    notes: '아홀로틀 펠릿·냉동 블러드웜·수조 쿨러.',
  },
  {
    id: 'sh-songpa-sugar',
    name: '슈가캐슬',
    kind: 'both',
    address: '서울 송파구 가락로 200',
    district: '서울 송파구',
    lat: 37.4985,
    lng: 127.1183,
    online: 'https://sugarcastle.co.kr',
    supportedCategories: ['mammal'],
    notes: '슈가글라이더·페렛·헷지호그 사료/케이지 전문.',
  },
  {
    id: 'sh-mapo-arthropod',
    name: '홍대절지샵',
    kind: 'both',
    address: '서울 마포구 와우산로 94',
    district: '서울 마포구',
    lat: 37.5559,
    lng: 126.9255,
    online: 'https://arthroshop.kr',
    supportedCategories: ['arthropod'],
    notes: '타란튤라·전갈·노린재 사육장. 오프라인 분양은 별도 문의.',
  },
]
