import type { Shop } from './schema'

export const shopsMock: Shop[] = [
  {
    id: 'sh-jamsil-reptile',
    name: '잠실파충류전문샵',
    kind: 'both',
    address: '서울 송파구 송파대로 567',
    district: '서울 송파구',
    lat: 37.5097,
    lng: 127.106,
    online: 'https://smartstore.naver.com/jamsil-reptile',
    supportedCategories: ['reptile', 'amphibian'],
    notes: '현장 픽업/택배 모두 가능. 사육장·UVB·먹이 풀라인업.',
  },
  {
    id: 'sh-songpa-bugshop',
    name: '송파곤충마켓',
    kind: 'food',
    address: '서울 송파구 백제고분로 320',
    district: '서울 송파구',
    lat: 37.5074,
    lng: 127.1129,
    online: 'https://buggy.kr',
    supportedCategories: ['reptile', 'arthropod', 'bird'],
    notes: '귀뚜라미·둠비아·밀웜 정기 배송. 살아있는 먹이 신선도 보장.',
  },
  {
    id: 'sh-gangnam-birdmarket',
    name: '강남조류마켓',
    kind: 'equipment',
    address: '서울 강남구 테헤란로 152',
    district: '서울 강남구',
    lat: 37.5006,
    lng: 127.0364,
    online: 'https://birdmarket.kr',
    supportedCategories: ['bird'],
    notes: '대형 새장·횃대·자유비행용 케이지 전문.',
  },
  {
    id: 'sh-bundang-petplus',
    name: '분당특수동물용품샵',
    kind: 'both',
    address: '경기 성남시 분당구 정자로 100',
    district: '경기 성남시 분당구',
    lat: 37.3603,
    lng: 127.1188,
    online: null,
    supportedCategories: ['reptile', 'mammal', 'amphibian'],
    notes: '오프라인 매장에서 사육 환경 상담 가능.',
  },
  {
    id: 'sh-online-pettrarium',
    name: '펫트라리움 (온라인)',
    kind: 'both',
    address: null,
    district: null,
    lat: null,
    lng: null,
    online: 'https://pettrarium.com',
    supportedCategories: ['reptile', 'amphibian', 'arthropod'],
    notes: '온라인 전용 사육장·온습도계·UV램프 전문몰.',
  },
  {
    id: 'sh-online-cgd',
    name: 'Repashy CGD 코리아',
    kind: 'food',
    address: null,
    district: null,
    lat: null,
    lng: null,
    online: 'https://repashy.kr',
    supportedCategories: ['reptile'],
    notes: '크레스티드 게코 다이어트(CGD) 정품 수입 판매.',
  },
  {
    id: 'sh-online-axolotl',
    name: '아쿠아펫몰',
    kind: 'both',
    address: null,
    district: null,
    lat: null,
    lng: null,
    online: 'https://aquapetmall.kr',
    supportedCategories: ['amphibian'],
    notes: '아홀로틀 펠릿·냉동 블러드웜·수조 쿨러.',
  },
  {
    id: 'sh-songpa-sugar',
    name: '슈가캐슬',
    kind: 'both',
    address: '서울 송파구 가락로 200',
    district: '서울 송파구',
    lat: 37.4985,
    lng: 127.1183,
    online: 'https://sugarcastle.co.kr',
    supportedCategories: ['mammal'],
    notes: '슈가글라이더·페렛·헷지호그 사료/케이지 전문.',
  },
  {
    id: 'sh-mapo-arthropod',
    name: '홍대절지샵',
    kind: 'both',
    address: '서울 마포구 와우산로 94',
    district: '서울 마포구',
    lat: 37.5559,
    lng: 126.9255,
    online: 'https://arthroshop.kr',
    supportedCategories: ['arthropod'],
    notes: '타란튤라·전갈·노린재 사육장. 오프라인 분양은 별도 문의.',
  },
  {
    id: 'sh-thezoo',
    name: '더쥬 (The Zoo)',
    kind: 'both',
    address: '서울 강남구 압구정로 (오프라인 매장)',
    district: '서울 강남구',
    lat: 37.5236,
    lng: 127.0287,
    online: 'https://xn--9m1b023b.com/',
    supportedCategories: ['reptile', 'amphibian', 'arthropod'],
    notes: '게코·뱀·도마뱀·개구리·먹이까지 한 사이트에서 배송. 입문 셋트 큐레이션 강함.',
  },
  {
    id: 'sh-newrun',
    name: '뉴런쥬라기',
    kind: 'both',
    address: '경기 안양시 동안구 동안로 (오프라인)',
    district: '경기 안양시',
    lat: 37.3925,
    lng: 126.953,
    online: 'https://newrunreptile.co.kr/',
    supportedCategories: ['reptile', 'amphibian'],
    notes: '레오·크레·볼파이톤 분양 + 사육 도구 일괄. 베이비~성체.',
  },
  {
    id: 'sh-mimine',
    name: '미미네아쿠아',
    kind: 'both',
    address: '서울 강서구 마곡중앙로 161',
    district: '서울 강서구',
    lat: 37.5683,
    lng: 126.8266,
    online: 'https://mimineaqua.co.kr/',
    supportedCategories: ['amphibian', 'reptile'],
    notes: '수족관 + 양서류·UVB·여과기·블러드웜 등 수서 종 필수품.',
  },
  {
    id: 'sh-themonster',
    name: '동탄파충류샵 더몬스터',
    kind: 'both',
    address: '경기 화성시 동탄대로 537',
    district: '경기 화성시',
    lat: 37.2003,
    lng: 127.0723,
    online: 'https://themonster.co.kr/',
    supportedCategories: ['reptile', 'amphibian', 'arthropod'],
    notes: '경기 남부 거점 파충류샵. 분양·사료·셋업까지 원스톱.',
  },
  {
    id: 'sh-rodent',
    name: '로던트 (Rodent)',
    kind: 'food',
    address: null,
    district: null,
    lat: null,
    lng: null,
    online: 'https://rodent.kr/',
    supportedCategories: ['reptile', 'amphibian'],
    notes: '귀뚜라미·밀웜·핑키 마우스 등 먹이 전용 브랜드. 정기 배송.',
  },
]
