import type { FuneralService } from './schema'

export const funeralMock: FuneralService[] = [
  {
    id: 'fn-21gram',
    name: '21그램 (21Gram)',
    url: 'https://www.21gram.co.kr',
    kind: 'memorial',
    region: '전국 (본사 경기 광주)',
    supportedCategories: ['mammal', 'bird', 'reptile', 'amphibian', 'arthropod'],
    description: '반려동물 화장 + 메모리얼 다이아몬드. 비대면 영상 추모식 운영.',
    certified: true,
    phone: '1670-9621',
  },
  {
    id: 'fn-petforest',
    name: '펫포레스트 (Pet Forest)',
    url: 'https://www.petforest.co.kr',
    kind: 'cremation',
    region: '경기 광주',
    supportedCategories: ['mammal', 'bird', 'reptile'],
    description: '농림축산식품부 등록 동물장묘업체. 화장 + 봉안당 + 수목장.',
    certified: true,
    phone: '031-768-7720',
  },
  {
    id: 'fn-petheaven',
    name: '펫헤븐 (Pet Heaven)',
    url: 'https://www.petheaven.co.kr',
    kind: 'cremation',
    region: '경기 김포',
    supportedCategories: ['mammal', 'bird'],
    description: '24시간 픽업, 개별 화장, 가족 입회.',
    certified: true,
  },
  {
    id: 'fn-petnara',
    name: '페트나라',
    url: 'https://www.petnara.com',
    kind: 'memorial',
    region: '서울 인근',
    supportedCategories: ['mammal', 'bird'],
    description: '메모리얼 액세서리, 유골 보관함, 추모 사진 서비스.',
    certified: true,
  },
  {
    id: 'fn-rainbow',
    name: '무지개다리 직거래 정보',
    url: 'https://www.animal.go.kr/front/community/show.do?boardId=funeral',
    kind: 'directory',
    region: '전국',
    supportedCategories: ['mammal', 'bird', 'reptile', 'amphibian', 'arthropod'],
    description: '농림축산검역본부 동물장묘업 등록 업체 검색 디렉토리.',
    certified: true,
  },
  {
    id: 'fn-petspa',
    name: '24시 펫스파 픽업',
    url: 'https://24petpickup.kr',
    kind: 'pickup',
    region: '수도권 24시',
    supportedCategories: ['mammal', 'bird'],
    description: '심야 픽업 + 화장장 인계 + 유골 배송.',
    certified: false,
    phone: '1577-0000',
  },
]
