import type { Community } from './schema'

export const communitiesMock: Community[] = [
  {
    id: 'cm-rcafe',
    name: '파충류 사육 카페 (네이버)',
    url: 'https://cafe.naver.com/reptiland',
    kind: 'cafe',
    language: 'ko',
    supportedCategories: ['reptile', 'amphibian'],
    memberHint: '회원 다수, 분양·정보 활성',
  },
  {
    id: 'cm-arthrokr',
    name: '한국절지동물협회 카페',
    url: 'https://cafe.naver.com/arthrokr',
    kind: 'cafe',
    language: 'ko',
    supportedCategories: ['arthropod'],
    memberHint: '타란튤라·전갈 정보 중심',
  },
  {
    id: 'cm-birdcafe',
    name: '앵무새 사육자 모임',
    url: 'https://cafe.naver.com/parrotkorea',
    kind: 'cafe',
    language: 'ko',
    supportedCategories: ['bird'],
    memberHint: '대형 종 위주',
  },
  {
    id: 'cm-amphi',
    name: '양서류 사육 정보',
    url: 'https://cafe.naver.com/amphikorea',
    kind: 'cafe',
    language: 'ko',
    supportedCategories: ['amphibian'],
    memberHint: '아홀로틀·도롱뇽 위주',
  },
  {
    id: 'cm-sugar',
    name: '슈가글라이더 사육자',
    url: 'https://cafe.naver.com/sugargliderkr',
    kind: 'cafe',
    language: 'ko',
    supportedCategories: ['mammal'],
    memberHint: '합사·분양 활성',
  },
  {
    id: 'cm-yt-leopard',
    name: 'Leopard Gecko 사육 채널',
    url: 'https://www.youtube.com/@LeopardGeckoCare',
    kind: 'youtube',
    language: 'en',
    supportedCategories: ['reptile'],
  },
  {
    id: 'cm-yt-axolotl',
    name: 'Axolotl Central',
    url: 'https://www.youtube.com/@AxolotlCentral',
    kind: 'youtube',
    language: 'en',
    supportedCategories: ['amphibian'],
  },
  {
    id: 'cm-discord-exotic',
    name: 'Exotic Pets Korea (Discord)',
    url: 'https://discord.gg/exoticpetskr',
    kind: 'discord',
    language: 'ko',
    supportedCategories: ['reptile', 'arthropod', 'amphibian', 'bird', 'mammal'],
  },
  {
    id: 'cm-dcr-reptile',
    name: 'DC 인사이드 파충류 갤러리',
    url: 'https://gall.dcinside.com/board/lists/?id=reptile',
    kind: 'forum',
    language: 'ko',
    supportedCategories: ['reptile'],
  },
]
