import type { QnaAnswer, QnaQuestion } from './schema'

export const SEED_QUESTIONS: QnaQuestion[] = [
  {
    id: 'seed-q-1',
    author: '거식이주인',
    speciesId: 'sp-leopard-gecko',
    category: 'reptile',
    title: '레오파드 게코가 2주째 거식인데 어떻게 해야 하나요?',
    body: '입양 3개월 차 레오파드 게코입니다. 보름 전부터 귀뚜라미를 거부하고 밀웜도 안 먹어요. 핫스팟 30℃, 쿨존 24℃로 유지 중이고 배변은 정상입니다. 체중은 아직 크게 안 빠졌는데 걱정됩니다.',
    tags: ['거식', '온도', '먹이'],
    baseVotes: 14,
    createdAt: '2026-05-18T11:00:00.000Z',
  },
  {
    id: 'seed-q-2',
    author: '타란초보',
    speciesId: 'sp-mexican-redknee',
    category: 'arthropod',
    title: '멕시칸 레드니 탈피 전 굶는 기간, 언제까지 정상인가요?',
    body: '복부가 거뭇해지고 3주째 먹이를 안 먹습니다. 굴 입구도 거미줄로 막아놨어요. 탈피 신호라고는 들었는데 이렇게 오래 굶어도 괜찮은지, 물그릇만 두면 되는지 궁금합니다.',
    tags: ['탈피', '거식', '습도'],
    baseVotes: 9,
    createdAt: '2026-05-21T15:30:00.000Z',
  },
  {
    id: 'seed-q-3',
    author: '우파집사',
    speciesId: 'sp-axolotl',
    category: 'amphibian',
    title: '아홀로틀 수조 수질, 암모니아가 자꾸 올라옵니다',
    body: '60L 수조에 아홀로틀 한 마리 사육 중입니다. 여과기를 돌리는데도 암모니아가 0.5ppm까지 올라와요. 수온은 17℃ 유지하고 있고 환수는 주 1회 30%씩 합니다. 아가미가 평소보다 안쪽으로 말려 있어 걱정입니다.',
    tags: ['수질', '암모니아', '환수'],
    baseVotes: 11,
    createdAt: '2026-05-24T09:20:00.000Z',
  },
  {
    id: 'seed-q-4',
    author: '비어디드초보',
    speciesId: 'sp-bearded-dragon',
    category: 'reptile',
    title: '비어디드 드래곤 UVB, 어떤 제품을 얼마 거리에 둬야 하나요?',
    body: '아성체 비어디드 드래곤을 120cm 사육장에서 키웁니다. UVB가 필수라고 들었는데 T5와 T8 중 뭘 쓰고, 바스킹 스팟에서 몇 cm 떨어뜨려야 하는지, 교체 주기는 어떻게 되는지 정리해주실 수 있을까요?',
    tags: ['UVB', '조명', '바스킹'],
    baseVotes: 18,
    createdAt: '2026-05-26T18:45:00.000Z',
  },
]

export const SEED_ANSWERS: QnaAnswer[] = [
  {
    id: 'seed-a-1a',
    questionId: 'seed-q-1',
    author: '게코마스터',
    body: '계절성 거식이거나 환경 스트레스일 가능성이 높습니다. 우선 핫스팟을 32℃까지 살짝 올리고, 은신처가 핫·쿨 양쪽에 다 있는지 확인하세요. 갓 탈피한 직후라면 며칠 더 굶을 수 있어 정상입니다. 체중을 주 1회 기록해서 10% 이상 빠지면 특수동물병원에 가세요.',
    baseVotes: 21,
    accepted: true,
    createdAt: '2026-05-18T12:10:00.000Z',
  },
  {
    id: 'seed-a-1b',
    questionId: 'seed-q-1',
    author: '파충류수의사',
    body: '배변이 정상이고 활동성이 유지된다면 급하게 강제 급여할 필요는 없습니다. 먹이 종류를 두카(둥근밀웜)나 레드러너로 바꿔보면 식욕이 돌아오는 경우도 많아요.',
    baseVotes: 8,
    accepted: false,
    createdAt: '2026-05-18T13:40:00.000Z',
  },
  {
    id: 'seed-a-2a',
    questionId: 'seed-q-2',
    author: '거미바라기',
    body: '정상입니다. 탈피 전에는 한 달 이상도 굶을 수 있어요. 굴을 막은 건 탈피 준비 신호이니 절대 건드리지 마세요. 물그릇은 깨끗하게 유지하고, 탈피 후 외골격이 굳는 24~48시간 동안은 먹이를 주지 마세요.',
    baseVotes: 15,
    accepted: true,
    createdAt: '2026-05-21T16:00:00.000Z',
  },
  {
    id: 'seed-a-3a',
    questionId: 'seed-q-3',
    author: '아쿠아도롱뇽',
    body: '암모니아 0.5ppm은 아홀로틀에게 위험합니다. 아가미가 말리는 건 수질 악화의 전형적 신호예요. 당장 50% 환수를 하고, 이후 며칠간 매일 20~30% 환수하면서 수치를 0으로 떨어뜨리세요. 여과재가 아직 박테리아 정착(사이클링) 전일 수 있으니 먹이량을 줄이고 찌꺼기를 즉시 제거하세요.',
    baseVotes: 17,
    accepted: true,
    createdAt: '2026-05-24T10:05:00.000Z',
  },
  {
    id: 'seed-a-3b',
    questionId: 'seed-q-3',
    author: '저온수조러',
    body: '추가로, 활성탄보다 생물학적 여과(스펀지 필터)를 늘리는 게 장기적으로 안정적입니다. 수류는 약하게 유지하세요. 아홀로틀은 강한 물살을 싫어합니다.',
    baseVotes: 6,
    accepted: false,
    createdAt: '2026-05-24T11:30:00.000Z',
  },
  {
    id: 'seed-a-4a',
    questionId: 'seed-q-4',
    author: '드래곤키퍼',
    body: 'T5 HO 형광등을 강력 추천합니다. T8보다 출력이 높아 큰 사육장에 적합해요. 바스킹 스팟에서 30~35cm 거리에 메시(철망) 없이 두고, 메시를 통과한다면 거리를 더 좁히세요. UVB 형광등은 빛이 나와도 자외선 출력은 6~12개월이면 떨어지므로 솔라미터로 측정하거나 6개월마다 교체하는 게 안전합니다.',
    baseVotes: 24,
    accepted: true,
    createdAt: '2026-05-26T19:30:00.000Z',
  },
  {
    id: 'seed-a-4b',
    questionId: 'seed-q-4',
    author: '햇빛도마뱀',
    body: 'UVI(자외선 지수) 기준으로 바스킹 존에서 3~4 정도가 이상적입니다. 아크릴은 UVB를 차단하니 사육장 뚜껑을 철망으로 쓰세요.',
    baseVotes: 7,
    accepted: false,
    createdAt: '2026-05-26T20:15:00.000Z',
  },
]
