import type { Species } from './schema'

export const speciesMock: Species[] = [
  {
    id: 'sp-leopard-gecko',
    slug: 'leopard-gecko',
    koreanName: '레오파드 게코',
    scientificName: 'Eublepharis macularius',
    category: 'reptile',
    difficulty: 'beginner',
    lifespanMinYears: 10,
    lifespanMaxYears: 20,
    summary: '온순하고 야행성인 입문용 도마뱀. 사육 공간이 작아도 충분합니다.',
    environment: '주간 28~32℃, 야간 22~25℃ / 습도 30~40% / 30×30×30cm 이상 사육장',
    diet: '귀뚜라미, 밀웜, 영양제 더스팅 주 2회',
    heroEmoji: '🦎',
    tags: ['야행성', '입문', '저소음'],
    spaceNeed: 'small',
    handlingTolerance: 'medium',
    activityPattern: 'nocturnal',
    beginnerTip: '핫스팟·쿨존 온도 구배가 가장 중요합니다. 디지털 온도계 2개를 양쪽에 두세요.',
    commonProblem: '탈피 잔존물(발가락·꼬리 끝)이 남으면 괴사 위험. 미스팅으로 습도 보조.',
    monthlyBudgetKrw: 30000,
  },
  {
    id: 'sp-crested-gecko',
    slug: 'crested-gecko',
    koreanName: '크레스티드 게코',
    scientificName: 'Correlophus ciliatus',
    category: 'reptile',
    difficulty: 'beginner',
    lifespanMinYears: 10,
    lifespanMaxYears: 18,
    summary: '점프력이 좋고 핸들링이 쉬운 입문용 수목성 도마뱀.',
    environment: '22~27℃ / 습도 60~80% / 수직형 사육장 30×30×45cm 이상',
    diet: 'CGD(크레스티드 게코 다이어트) 가루 + 곤충 간식',
    heroEmoji: '🦎',
    tags: ['수목성', '입문', '점프'],
    spaceNeed: 'small',
    handlingTolerance: 'high',
    activityPattern: 'nocturnal',
    beginnerTip: 'CGD 한 통으로 한 달 이상 급여 가능 — 곤충 직접 다루기 부담 적음.',
    commonProblem: '스트레스 시 꼬리 자절(재생 안 됨). 핸들링 5분 이하로 시작.',
    monthlyBudgetKrw: 25000,
  },
  {
    id: 'sp-ball-python',
    slug: 'ball-python',
    koreanName: '볼파이톤',
    scientificName: 'Python regius',
    category: 'reptile',
    difficulty: 'intermediate',
    lifespanMinYears: 20,
    lifespanMaxYears: 30,
    summary: '온순한 성격의 보아과 뱀. 다양한 모프(색상)로 인기.',
    environment: '주간 28~32℃ 핫스팟, 야간 24℃ / 습도 50~60% / 90×45×45cm',
    diet: '주 1회 적당 크기 마우스/래트',
    heroEmoji: '🐍',
    tags: ['모프', '대형', '보온 필요'],
    spaceNeed: 'medium',
    handlingTolerance: 'medium',
    activityPattern: 'nocturnal',
    beginnerTip: '온습도 조절기(서모스탯) 필수. 직접 보온등에 닿으면 화상.',
    commonProblem: '거식(refusal to eat) — 환경 스트레스가 대부분 원인. 사육장을 어둡게.',
    monthlyBudgetKrw: 40000,
  },
  {
    id: 'sp-russian-tortoise',
    slug: 'russian-tortoise',
    koreanName: '러시안 육지거북',
    scientificName: 'Testudo horsfieldii',
    category: 'reptile',
    difficulty: 'intermediate',
    lifespanMinYears: 40,
    lifespanMaxYears: 50,
    summary: '활동적이고 굴 파기를 좋아하는 소형 육지거북.',
    environment: '바스킹 32~35℃ / 자외선 UVB 필수 / 90×45cm 이상',
    diet: '잎채소, 야생 잡초, 칼슘 보충',
    heroEmoji: '🐢',
    tags: ['장수', 'UVB', '활동적'],
    spaceNeed: 'large',
    handlingTolerance: 'low',
    activityPattern: 'diurnal',
    beginnerTip: 'UVB 램프는 6개월~1년에 한 번 교체. 가시광선과는 다릅니다.',
    commonProblem: 'MBD(대사성 골질환) — UVB 부족·칼슘 미공급 시 갑이 휨.',
    monthlyBudgetKrw: 35000,
  },
  {
    id: 'sp-mexican-redknee',
    slug: 'mexican-redknee-tarantula',
    koreanName: '멕시칸 레드니 타란튤라',
    scientificName: 'Brachypelma hamorii',
    category: 'arthropod',
    difficulty: 'beginner',
    lifespanMinYears: 15,
    lifespanMaxYears: 30,
    summary: '온순하고 색이 화려한 입문용 타란튤라.',
    environment: '24~28℃ / 습도 60~70% / 20×20cm 폴리카보네이트',
    diet: '주 1회 귀뚜라미 또는 둠비아 로치',
    heroEmoji: '🕷️',
    tags: ['독성낮음', '관상', '저활동'],
    spaceNeed: 'small',
    handlingTolerance: 'low',
    activityPattern: 'nocturnal',
    beginnerTip: '관상 위주 — 잘 움직이지 않아 보기에는 단조롭지만 평생 사육 가능.',
    commonProblem: '복부 자극모(urticating hair)가 알레르기 유발. 얼굴 근처 접근 금지.',
    monthlyBudgetKrw: 10000,
  },
  {
    id: 'sp-emperor-scorpion',
    slug: 'emperor-scorpion',
    koreanName: '엠퍼러 스콜피온',
    scientificName: 'Pandinus imperator',
    category: 'arthropod',
    difficulty: 'intermediate',
    lifespanMinYears: 6,
    lifespanMaxYears: 8,
    summary: '대형 검은 전갈로 독성이 약하고 야행성.',
    environment: '26~30℃ / 습도 70~80% / 코코피트 깊은 바닥재',
    diet: '귀뚜라미, 밀웜, 작은 도마뱀',
    heroEmoji: '🦂',
    tags: ['야행성', '습한환경', '굴파기'],
    spaceNeed: 'small',
    handlingTolerance: 'low',
    activityPattern: 'nocturnal',
    beginnerTip: '굴 파기 본성 — 바닥재는 10cm 이상 깊게.',
    commonProblem: '독성은 약하지만 알레르기·면역 저하자에게는 위험. 핸들링 자제.',
    monthlyBudgetKrw: 15000,
  },
  {
    id: 'sp-cockatiel',
    slug: 'cockatiel',
    koreanName: '왕관앵무 (코카티엘)',
    scientificName: 'Nymphicus hollandicus',
    category: 'bird',
    difficulty: 'intermediate',
    lifespanMinYears: 15,
    lifespanMaxYears: 25,
    summary: '사회성이 높고 휘파람을 따라 부르는 중형 앵무.',
    environment: '실내 18~28℃ / 새장 60×40×60cm 이상 + 자유 비행 시간',
    diet: '시드믹스 + 펠릿 + 채소/과일',
    heroEmoji: '🦜',
    tags: ['사회성', '음성모방', '날개관리'],
    spaceNeed: 'medium',
    handlingTolerance: 'high',
    activityPattern: 'diurnal',
    beginnerTip: '매일 2시간 이상 새장 밖 비행이 필수. 외출 시 창문 닫기.',
    commonProblem: 'PBFD·앵무폴리오마 등 바이러스 — 분양 시 검진 이력 확인.',
    monthlyBudgetKrw: 50000,
  },
  {
    id: 'sp-axolotl',
    slug: 'axolotl',
    koreanName: '아홀로틀',
    scientificName: 'Ambystoma mexicanum',
    category: 'amphibian',
    difficulty: 'intermediate',
    lifespanMinYears: 10,
    lifespanMaxYears: 15,
    summary: '평생 유생 형태로 사는 멕시코산 도롱뇽. 수족관 사육.',
    environment: '수온 16~18℃ (저온 유지) / pH 7~8 / 60L 이상 수조',
    diet: '아홀로틀 펠릿, 냉동 블러드웜, 갯지렁이',
    heroEmoji: '🐠',
    tags: ['저온수조', '재생능력', '소음없음'],
    spaceNeed: 'medium',
    handlingTolerance: 'low',
    activityPattern: 'mixed',
    beginnerTip: '여름 수온 관리가 핵심 — 18℃ 넘으면 스트레스, 24℃ 이상에서 폐사.',
    commonProblem: '곰팡이성 감염 — 수질 악화·고온 시 발생. 정기 환수.',
    monthlyBudgetKrw: 60000,
  },
  {
    id: 'sp-sugar-glider',
    slug: 'sugar-glider',
    koreanName: '슈가글라이더',
    scientificName: 'Petaurus breviceps',
    category: 'mammal',
    difficulty: 'advanced',
    lifespanMinYears: 10,
    lifespanMaxYears: 15,
    summary: '활공하는 야행성 유대류. 2마리 이상 합사 권장.',
    environment: '18~28℃ / 수직형 대형 케이지 90×60×180cm / 사회성 필요',
    diet: 'TPG/HPW 식단 + 곤충 + 과일',
    heroEmoji: '🐿️',
    tags: ['야행성', '합사필수', '식단복잡'],
    spaceNeed: 'large',
    handlingTolerance: 'medium',
    activityPattern: 'nocturnal',
    beginnerTip: '단독 사육 금지 — 우울증·자해 발생. 동성 2마리 이상 합사.',
    commonProblem: '대사성 골질환 + 영양 결핍 — TPG/HPW 정확한 비율 필수.',
    monthlyBudgetKrw: 80000,
  },
  {
    id: 'sp-hedgehog',
    slug: 'african-pygmy-hedgehog',
    koreanName: '아프리칸 피그미 헷지호그',
    scientificName: 'Atelerix albiventris',
    category: 'mammal',
    difficulty: 'intermediate',
    lifespanMinYears: 4,
    lifespanMaxYears: 7,
    summary: '단독 사육 야행성 식충 포유류. 보온이 중요합니다.',
    environment: '실내 24~28℃ 유지 / 80×50cm 케이지 + 휠',
    diet: '고단백 고양이 사료 + 곤충 간식',
    heroEmoji: '🦔',
    tags: ['단독사육', '보온필수', '야행성'],
    spaceNeed: 'medium',
    handlingTolerance: 'medium',
    activityPattern: 'nocturnal',
    beginnerTip: '겨울철 보온 — 22℃ 이하면 동면 시도 후 깨어나지 못할 수 있음.',
    commonProblem: 'WHS(Wobbly Hedgehog Syndrome) — 유전성 신경질환, 치료 불가.',
    monthlyBudgetKrw: 45000,
  },
]

export function findSpeciesById(id: string): Species | undefined {
  return speciesMock.find((s) => s.id === id || s.slug === id)
}

export function getSpeciesByCategory(category: Species['category']): Species[] {
  return speciesMock.filter((s) => s.category === category)
}
